spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: ${OAUTH_ISSUER_URL}
